name: Deploy

on:
  release:
    types: [created]
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Vite build
        run: yarn install --frozen-lockfile
        run: yarn build

      - name: Relesae branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release
          publish_dir: ./dist

      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 8m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /usr/local/wwwroot/veact-admin/
            echo "[deploy] pulling source code..."
            git fetch --all && git reset --hard origin/release && git pull
            git checkout release
            echo "[deploy] done"
